APP_ID_REQUIRED = 'app id is required'
CREDENTIAL_BASIC_AUTH_REQUIRED = 'credential basic auth is required'
DOMAIN_REQUIRED = 'domain is required'
ENDPOINT_REGION_INVALID = 'endpoint region invalid'
ENDPOINT_REGION_REQUIRED = 'endpoint region is required'
